In [8]:
#importing neccesary libraries
import numpy as np
import pandas as pd


In [ ]:
#creating a function that swaps different rows of matrix
def swap_rows(M, row_index_1, row_index_2):
    #copy the matrix
    M = M.copy()
    # swap indexes (you use a list of indexes to index rows in Numpy)
    M[[row_index_1, row_index_2]] = M[[row_index_2, row_index_1]]
    #return the swapped matrices
    return M




In [9]:
M = np.array([
[1, 3, 6],
[0, -5, 2],
[-4, 5, 8]
])
print(M)

[[ 1  3  6]
 [ 0 -5  2]
 [-4  5  8]]


In [13]:
swap_rows(M,0,2)

array([[-4,  5,  8],
       [ 0, -5,  2],
       [ 1,  3,  6]])