In [8]:
#importing neccesary libraries
import numpy as np
import pandas as pd


In [ ]:
#creating a function that swaps different rows of matrix
def swap_rows(M, row_index_1, row_index_2):
    #copy the matrix
    M = M.copy()
    # swap indexes (you use a list of indexes to index rows in Numpy)
    M[[row_index_1, row_index_2]] = M[[row_index_2, row_index_1]]
    #return the swapped matrices
    return M




In [9]:
M = np.array([
[1, 3, 6],
[0, -5, 2],
[-4, 5, 8]
])
print(M)

[[ 1  3  6]
 [ 0 -5  2]
 [-4  5  8]]


In [13]:
swap_rows(M,0,2)

array([[-4,  5,  8],
       [ 0, -5,  2],
       [ 1,  3,  6]])

In [18]:
def getting_first_non_zero_from_column(M,column,starting_row):

    Arrays = M[starting_row:, column]
    
    for i, val in enumerate(Arrays):
        if not np.isclose(val, 0, atol = 1e-5):
            index = i + starting_row
            return index
    return -1


In [16]:
N = np.array([
[0, 5, -3 ,6 ,8],
[0, 6, 3, 8, 1],
[0, 0, 0, 0, 0],
[0, 0, 0 ,0 ,7],
[0, 2, 1, 0, 4]
]
)
print(N)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]


In [19]:
getting_first_non_zero_from_column(N, column = 0, starting_row = 0)

-1

In [20]:
getting_first_non_zero_from_column(N, column = -1, starting_row = 2)

3